CREATE TABLE User(
	Email	CHAR(20)	NOT NULL,
	Password CHAR	NOT NULL,
	Karma	INT,
	UserID CHAR(10)	NOT NULL,
	Username CHAR(10)	NOT NULL,
	PRIMARY KEY (Username) 
);

CREATE TABLE Administrator(
	Admin_access_level INT,
	UserID CHAR(10)	NOT NULL,
	AdminID CHAR(10) NOT NULL,
	PRIMARY KEY (UserID),
	FOREIGN KEY (Username) REFERENCES User (UserID) ON DELETE CASCADE
);

CREATE TABLE LocationOf(
	Latitude DECIMAL(8,6)		NOT NULL,
	Longitude DECIMAL(8,6)		NOT NULL,
	Address CHAR(50),
	Time CHAR(20),
	PRIMARY KEY (Latitude, Longitude),
    FOREIGN KEY (UserID) REFERENCES User (User) ON DELETE CASCADE
    FOREIGN KEY (PostID) REFERENCES Post (Post) ON DELETE CASCADE

);

CREATE TABLE Post(
	PostID CHAR(10)	NOT NULL,
	Content CHAR(200)	NOT NULL,
	UserID CHAR(10)	NOT NULL,
	Time CHAR(20)	NOT NULL,
	PRIMARY KEY(PostID),
	FOREIGN KEY (UserID) REFERENCES User (UserID) ON DELETE CASCADE
);

CREATE TABLE PhotoIn(
	PhotoID CHAR(10)	NOT NULL,
	Size INT		NOT NULL,
	Format CHAR(100)	NOT NULL,
	PostID CHAR(100)	NOT NULL,
	PRIMARY KEY(PostID, PhotoID),
	FOREIGN KEY (PostID) REFERENCES Post (PostID) ON DELETE CASCADE
);

CREATE TABLE LikedPost(
	PostID CHAR(10)	NOT NULL,
	Trending BOOLEAN,
	#ofLikes INT	NOT NULL,
    PRIMARY KEY (PostID),
	FOREIGN KEY (PostID) REFERENCES Post (PostID) ON DELETE CASCADE
);

CREATE TABLE TrendingTopic(
	TopicID CHAR(10)	NOT NULL, 
    Content CHAR 50	NOT NULL, 
    PostID CHAR(10)	NOT NULL,
    PRIMARY KEY (TopicID),
	FOREIGN KEY (PostID) REFERENCES Post (PostID) ON DELETE NO ACTION
);

CREATE TABLE VoteFor(
	VoteID CHAR(20)	
    Type BOOLEAN	
    Time CHAR(20)	
    UserID CHAR(10)	NOT NULL,
    PostID CHAR(20)	NOT NULL,
    PRIMARY KEY (VoteID),
    FOREIGN KEY (UserID) REFERENCES User (UserID) ON DELETE CASCADE,
    FOREIGN KEY (PostID) REFERENCES Post (PostID) ON DELETE CASCADE
);

CREATE TABLE Comment(
	CommentID CHAR(20)	NOT NULL, 
    UserID CHAR(10)		NOT NULL,
    PostID CHAR(20)		NOT NULL,
    Time CHAR(20)		NOT NULL,
    Content CHAR(200)		NOT NULL,
    PRIMARY KEY (CommentID),
    FOREIGN KEY (UserID) REFERENCES Post (UserID) ON DELETE CASCADE
    FOREIGN KEY (PostID) REFERENCES Post (PostID) ON DELETE CASCADE
);

CREATE TABLE ReplyTo(
	ReplyID CHAR(20)		NOT NULL, 
    UserID CHAR(10)		NOT NULL, 
    CommentID CHAR(20)	NOT NULL, 
    Content CHAR(100)		NOT NULL, 
    Time CHAR(20)		NOT NULL,
    PRIMARY KEY (ReplyID),
    FOREIGN KEY (UserID) REFERENCES Post (User) ON DELETE CASCADE
    FOREIGN KEY (CommentID) REFERENCES Comment (CommentID) ON DELETE CASCADE
);
